name: modular

packages:
  - apps/**
  - packages/**
scripts:
  formatting:check: melos exec -- dart format --set-exit-if-changed .

  analyze: melos exec -- dart analyze --fatal-infos

  run:app:
    run: melos exec --  flutter run --debug -d emulator-5554
    select-package:
      scope: 'flutter_bilibili'
dependencies:
  logger: ^1.1.0
